### ISSUE TITLE
Missing gnomad_cpsr.vcf.gz

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/cpsr#17]
Hey Sigve,

Trying to run the new CPSR through hg38. `data/grch38/gnomad_cpsr/gnomad_cpsr.vcf.gz` seems to be missing from the bundle. I might have deleted it accidentally on my side, will try to download again... Can you check on your side if it's there or not?

Vlad

**Comment by sigven** [comment]
You are right, Vlad. Updated bundle shortly!

best,
Sigve

**Comment by sigven** [comment]
Hi Vlad,
I will post a NEWS item on the CPSR page with a link to the missing files (rather than updating the whole bundle). Would you mind checking that [this gdrive link](https://drive.google.com/open?id=13mOn1WXEXz_XO3N57LC415gPO0kz3oRA) provides the necessary data?

best,
Sigve

**Comment by vladsaveliev** [comment]
Thanks Sigve! It works
