### ISSUE TITLE
ERROR while running

### ISSUE THREAD

**Issue by kokyriakidis** [sigven/cpsr#23]
Hi @sigven !

I am facing the following errors while running the tool
```
2019-11-25 21:08:34 - cpsr-validate-input - ERROR - 
2019-11-25 21:08:34 - cpsr-validate-input - ERROR - According to the VCF specification, the VCF file (/workdir/input_vcf/SRR9873696-ensemble-annotated.vcf.gz) is NOT valid:
ERROR: Line 2843: Metadata ID contains a character different from alphanumeric, dot, underscore and dash
ERROR: Line 2844: Metadata ID contains a character different from alphanumeric, dot, underscore and dash
ERROR: Line 2845: Metadata ID contains a character different from alphanumeric, dot, underscore and dash
ERROR: Line 2846: Metadata ID contains a character different from alphanumeric, dot, underscore and dash
.......
.......
ERROR: Line 153128: Sample #1, PL=90,0 does not match the meta specification Number=G (contains 2 value(s), expected 3)
ERROR: Line 153129: Sample #1, PL=45,0 does not match the meta specification Number=G (contains 2 value(s), expected 3)
ERROR: Line 153130: Sample #1, PL=45,0 does not match the meta specification Number=G (contains 2 value(s), expected 3)
```

The vcf file is
[SRR9873696.vcf.gz](https://github.com/sigven/cpsr/files/3888037/SRR9873696.vcf.gz)

Any thoughts?

**Comment by sigven** [comment]
Hi @kokyriakidis!

This indicates that your VCF file do not adhere to the (very) strict requirements for the VCF format, as tested by [vcf-validator](https://github.com/EBIvariation/vcf-validator). Unless you want to fix your VCF so that it fully adheres to the VCF format, you may try adding the option `--no_vcf_validate`. That usually helps.

best,
Sigve

**Comment by kokyriakidis** [comment]
It works! Just wanted to ask if panel 0 has all the genes on all the other panels you offer.

**Comment by sigven** [comment]
No, Panel 0 is assembled from other sources than Genomics England, documented here: https://github.com/sigven/cpsr#cancer-predisposition-genes

But I would expect a significant overlap.

Sigve
