### ISSUE TITLE
cpsr_validate_input.py: error: argument vcf_validation: invalid int value: '/home/zdjzyx01/biosoft/cpsr/cpsr.toml'

### ISSUE THREAD

**Issue by jxshi** [sigven/cpsr#24]
Hi @sigven ,

I have upgrade to the latest version of ```PCGR``` and ```CPSR```. ```PCGR``` program works like charm, but the ```CPSR``` program doesn't seem to work.
Here is the command I used to run ```CPSR```.
```
python /home/zdjzyx01/biosoft/cpsr/cpsr.py  /home/zdjzyx01/MDT/proj/research/1000g/raw/2019-09-17_HNQ0456-decomposed.vcf.gz /home/zdjzyx01/biosoft/pcgr/ /home/zdjzyx01/MDT/proj/research/1000g/HNQ0456 grch37 /home/zdjzyx01/biosoft/cpsr/cpsr.toml HNQ0456new --no_vcf_validate --no-docker --panel_id 0
```

```
2019-11-30 22:32:46 - cpsr-validate-input - INFO - STEP 0: Validate input data
usage: cpsr_validate_input.py [-h] [--output_dir OUTPUT_DIR] [--debug]
                              pcgr_dir input_vcf configuration_file {0,1}
                              genome_assembly virtual_panel_id {0,1}
cpsr_validate_input.py: error: argument vcf_validation: invalid int value: '/home/zdjzyx01/biosoft/cpsr/cpsr.toml'
```
Any idea how to solve this problem?

Thanks!

Best,
Jianxiang

**Comment by sigven** [comment]
Hi @jxshi,
I notice you are using the `--no-docker`option. Perhaps the no-docker version is not fully up-to-date, @vladsaveliev?

best,
Sigve

**Comment by vladsaveliev** [comment]
Hi, that's right, the latest version is not yet on conda - but it will be later today. I'll let you know!

**Comment by vladsaveliev** [comment]
Done now. @jxshi, please update the conda packages with:

```
conda install -c pcgr -c conda-forge -c bioconda pcgr==0.8.4.3 cpsr==0.5.2.2 
```

And see if it works for you now?

**Comment by jxshi** [comment]
Hi @vladsaveliev ,

Thank you for your timely reply. But there seemed new error message:
```
Traceback (most recent call last):
  File "/home/zdjzyx01/biosoft/cpsr/cpsr.py", line 629, in <module>
    if __name__=="__main__": __main__()
  File "/home/zdjzyx01/biosoft/cpsr/cpsr.py", line 180, in __main__
    run_cpsr(host_directories, docker_image_version, config_options, args.sample_id, virtual_panel_id, args.genome_assembly, cpsr_version, args.no_vcf_validate, diagnostic_grade_only, args.basic, debug = args.debug, docker_user_id=args.docker_user_id)
  File "/home/zdjzyx01/biosoft/cpsr/cpsr.py", line 551, in run_cpsr
    assert os.path.isdir(loftee_dir), 'LoF VEP plugin is not found in ' + loftee_dir + '. Please make sure you installed pcgr conda package and have corresponding conda environment active.'
AssertionError: LoF VEP plugin is not found in /home/zdjzyx01/miniconda3/envs/pcgr/share/loftee. Please make sure you installed pcgr conda package and have corresponding conda environment active.
```
Can you check further please?

Thanks!

Jianxiang

**Comment by vladsaveliev** [comment]
@jxshi, sorry about this. Gonna need https://github.com/bioconda/bioconda-recipes/pull/18392 to be resolved to make LoF VEP plugin available on conda - I will try to escalate this.

**Comment by vladsaveliev** [comment]
Good news, the perl-big-file recipe for conda was merged, and it works with CPSR on my side. So now I need to rebuild the `pcgr` and `cpsr` packages. Will let you know once they are uploaded

**Comment by vladsaveliev** [comment]
Alright. @jxshi, now if you update the pcgr package using the following command, it should hopefully work:

```
conda install -c pcgr -c conda-forge -c bioconda pcgr==0.8.4.4 
```

**Comment by jxshi** [comment]
Thank you for keeping me informed. I will try again later.

Sent from my iPhone

On Dec 7, 2019, at 10:05 AM, Vlad Saveliev <notifications@github.com<mailto:notifications@github.com>> wrote:


Alright. @jxshi<https://github.com/jxshi>, now if you update the pcgr package using the following command, it should hopefully work:

conda install -c pcgr -c conda-forge -c bioconda pcgr==0.8.4.4

**Comment by jxshi** [comment]
Hi @vladsaveliev ,

There might still be something wrong. ```Conda``` cannot find ```pcgr==0.8.4.4``` in the conda channel. Here is the error message:
```
PackagesNotFoundError: The following packages are not available from current channels:

  - pcgr==0.8.4.4

Current channels:

  - https://conda.anaconda.org/pcgr/linux-64
  - https://conda.anaconda.org/pcgr/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
Thank you for your time. Appreciate it.

Jianxiang

**Comment by vladsaveliev** [comment]
@jxshi, sorry, my fault, I uploaded the package into a wrong channel. Can you try again please? Sorry for all the trial-and-error...

**Comment by jxshi** [comment]
Hi @vladsaveliev ,

Thank you for your timely reply. I am able to get ```cpsr``` run on the cluster now. 

Cheers!

All the best,
Jianxiang
