### ISSUE TITLE
Error in loadNamespace(name) : there is no package called 'reactable'

### ISSUE THREAD

**Issue by brucemoran** [sigven/cpsr#29]
Hi Sigve,

have updated to version 0.6.0rc, installed via conda, and I get the above error during `### Annotation resources`.

Presume that `reactable` wasn't added to your conda channel?

Thanks for all the updates,

Bruce

**Comment by sigven** [comment]
Hi Bruce,

Conda updates are still in the making, as stated in the NEWS item. 

Will notify when Conda is updated as well.

Regards,
Sigve

**Comment by brucemoran** [comment]
Sorry, never saw it, thanks for reply.
