### ISSUE TITLE
x object 'GWAS_CITATION' not found

### ISSUE THREAD

**Issue by brucemoran** [sigven/cpsr#30]
Hi Sigve,

I'm getting the below error.

Can you give an idea?

VCF: [test.hc.merge.vcf.gz](https://github.com/sigven/cpsr/files/5324289/test.hc.merge.vcf.gz)

Singularity container is library://bruce.moran/default/projects:somatic_n-of-1.centos7.conda.

Command:
```
cpsr.py  \  
  --no-docker  \
  --no_vcf_validate \
  --panel_id 0 \
  --query_vcf test.hc.merge.vcf.gz \
  --pcgr_dir pcgr \
  --output_dir ./ \
  --genome_assembly grch38 \
  --conf pcgr/data/grch38/cpsr_configuration_default.toml \
  --sample_id test
```
```
Error: Problem with `filter()` input `..1`.
x object 'GWAS_CITATION' not found
i Input `..1` is `!is.na(GWAS_HIT) & !is.na(GWAS_CITATION)`.
Backtrace:
    x
 1. +-pcgrr::generate_cpsr_report(...)
 2. | +-dplyr::filter(calls, !is.na(GWAS_HIT) & !is.na(GWAS_CITATION))
 3. | \-dplyr:::filter.data.frame(calls, !is.na(GWAS_HIT) & !is.na(GWAS_CITATION))
 4. |   \-dplyr:::filter_rows(.data, ...)
 5. |     +-base::withCallingHandlers(...)
 6. |     \-mask$eval_all_filter(dots, env_filter)
 7. \-base::.handleSimpleError(...)
 8.   \-dplyr:::h(simpleError(msg, call))
```

**Comment by sigven** [comment]
Thanks for reporting. I'll have a look.

**Comment by sigven** [comment]
Hi Bruce,

Figured it out. Try making your Singularity version with the dev version of PCGR (`docker pull sigven/pcgr:dev`), and clone the updated `cpsr.py` script from the repo. I believe your test run should work now.

thanks,
Sigve

**Comment by brucemoran** [comment]
Thanks Sigve,

I'm just going to roll back to previous versions as I make one big
container for my workflow from conda, so would need to set up a lot of
things to make it work, when previous does the job!

Appreciate the quick responses as ever,

Bruce
