### ISSUE TITLE
ImportError: No module named toml

### ISSUE THREAD

**Issue by hmalcaraz** [sigven/cpsr#32]
Hello Sigve,

Hope you are in good health. I encountered an error using MacOS PyCharm, Python interpreter 3.9, pip version 20.3.3 and later version 21.0.1., line 12, in <module>, Import error no module named toml.  

Would you have any suggestions?

**Comment by sigven** [comment]
Hi,

Please follow the installation instructions outlined, you probably have not installed the toml library:
https://github.com/sigven/cpsr#step-0-python

Also not that CPSR is set up for Python v3.6, I would recommend setting up a Conda environment with Python 3.6 and install the toml library there.

kind regards,
Sigve
