### ISSUE TITLE
Error: `x` and `y` must share the same src

### ISSUE THREAD

**Issue by brucemoran** [sigven/cpsr#34]
Hi again,

have an error on cpsr.py 0.6.1 using latest data bundle (20201123) (NB pcgr.py is `dev`):

```
Error: `x` and `y` must share the same src, set `copy` = TRUE (may be slow).
Backtrace:
     x
  1. +-pcgrr::generate_cpsr_report(...)
  2. | +-`%>%`(...)
  3. | \-pcgrr::assign_pathogenicity_evidence(...)
  4. |   +-dplyr::left_join(...)
  5. |   \-dplyr:::left_join.data.frame(...)
  6. |     \-dplyr::auto_copy(x, y, copy = copy)
  7. |       \-dplyr:::glubort(...)
  8. +-pcgrr::detect_cancer_traits_clinvar(...)
  9. | \-base::nrow(cpg_calls)
 10. \-pcgrr::determine_pathogenicity_classification(.)
 ```

Dies with this after line: 
```
2021-02-17 08:30:26 [INFO] Number of non-coding variants in cancer predisposition genes: 38747
```

Can you see where error is from?

Command:
```
cpsr.py --no-docker \
        --no_vcf_validate \
        --panel_id 0 \
        --query_vcf sample.hc.merge.vcf.gz \
        --pcgr_dir pcgr \
        --output_dir ./ \
        --genome_assembly grch38 \
        --conf pcgr/data/grch38/cpsr_configuration_default.toml \
        --sample_id $META
```

Thanks,

Bruce

**Comment by sigven** [comment]
Hi Bruce,
Thanks a lot for reporting. Could you share your input (sample.hc.merge.vcf.gz) as well?

Sigve

**Comment by brucemoran** [comment]
Hi Sigve,

shared with your gmail,

Bruce

**Comment by sigven** [comment]
Thanks Bruce, got it. Will look into it!  Again, thanks for reporting.

Sigve

**Comment by sigven** [comment]
Hmm, made an initial run on your test VCF with my Docker installation, and that went through just fine. Will next check also with the Conda version, to see whether that can reproduce the error. On another note:

Your VCF files contains a lot of spurious entries, both multiallelic sites, and variants with a `*`. Also, I am not confident that the VCF has been subject to any quality control with respect to depth etc; i see a lot of variants with very low depth. I strongly encourage to do some quality control of the VCF before feeding it for interpretation. 

Sigve

**Comment by brucemoran** [comment]
Hi Sigve,

OK thanks for looking into it. Might try rerunning with your docker. 

This is a control for benchmark of some filtering etc that I am working on, so indeed needs filtering etc!

Thanks, 

Bruce.
