### ISSUE TITLE
genes being excluded from CPSR exploratory track

### ISSUE THREAD

**Issue by MrsLaviniaG** [sigven/cpsr#35]
Hi Sigve

We are supplying a list of genes to CPSR using the _--custom_list_ option.
Several of those genes are not making it through to the final CPSR report.
Looking at the logs I can see:

_2021-02-18 21:31:44 - cpsr-validate-input - WARNING - Ignoring custom-provided gene symbol (ANKRD26) NOT found in CPSR exploratory track 0
2021-02-18 21:31:44 - cpsr-validate-input - WARNING - Choose only symbols from this set: https://github.com/sigven/cpsr/predisposition.md
2021-02-18 21:31:44 - cpsr-validate-input - WARNING - Ignoring custom-provided gene symbol (CSDE1) NOT found in CPSR exploratory track 0
2021-02-18 21:31:44 - cpsr-validate-input - WARNING - Choose only symbols from this set: https://github.com/sigven/cpsr/predisposition.md_

https://github.com/sigven/cpsr/predisposition.md does not exist, but https://github.com/sigven/cpsr/blob/master/predisposition.md does. That file **does** contain ANKRD26, but it **does not** contain CSDE1. Any insights greatly appreciated!

**Comment by sigven** [comment]
Hi Lavinia,

Thanks for reaching out. Can you send me the custom list file you are using, I am currently not able to reproduce the error on my side.

thanks,
Sigve

**Comment by sigven** [comment]
One more thing: Do you see ANKRD26 in `data/grch38/cpsr_exploratory_track.tsv`?

**Comment by MrsLaviniaG** [comment]
Thanks Sigve for responding so quickly!
We may be a version behind your latest update, I will confirm.

**Comment by MrsLaviniaG** [comment]
Neither of the genes that I mentioned is in the file data/grch38/cpsr_exploratory_track.tsv. Thanks for that, very helpful with troubleshooting. I will update our version and get back to you.

**Comment by MrsLaviniaG** [comment]
Thanks for your help Sigve, I can see ANKRD26 in the latest version of the data bundle, and I now understand why CSDE1 was omitted.
