### ISSUE TITLE
Not able to download the data bundles (404 Error)

### ISSUE THREAD

**Issue by ashishjain1988** [sigven/cpsr#36]
I am not able to download the data bundles for both hg38 and hg37 genomes. I am getting a 404 error.

wget http://insilico.hpc.uio.no/pcgr/pcgr.databundle.20201123.grch37.tar.gz -O grch37.tar.gz
--2021-02-23 12:10:24--  http://insilico.hpc.uio.no/pcgr/pcgr.databundle.20201123.grch37.tar.gz
Resolving dtn09-e0 (dtn09-e0)... 10.1.200.191
Connecting to dtn09-e0 (dtn09-e0)|10.1.200.191|:3128... connected.
Proxy request sent, awaiting response... 404 Not Found
2021-02-23 12:10:25 ERROR 404: Not Found.

**Comment by sigven** [comment]
The server is still being configured. If you read the instructions [here](https://github.com/sigven/pcgr#step-2-download-pcgr-and-data-bundle), there is an alternative download host.

**Comment by sigven** [comment]
Btw, you have your URL wrong: correct url is: http://insilico.hpc.uio.no/pcgr/pcgr.databundle.20201123.grch37.tgz
