### ISSUE TITLE
ACMG guideline updated to version 3.0. New genes were added to the secondary finding gene list.

### ISSUE THREAD

**Issue by jxshi** [sigven/cpsr#37]
Hi @sigven ,

ACMG has updated its recommendations for reporting incidental findings in clinical exome and genome sequencing and 14 genes were added:  ACVRL1, BTD, CASQ2, ENG, FLNC, GAA, HFE, HNF1A, MAX, PALB2, RPE65, TMEM127, TRDN, and TTN. . Here is the link to the report.

[ACMG Recommendations for Reporting of Incidental Findings in Clinical Exome and Genome Sequencing](https://www.ncbi.nlm.nih.gov/clinvar/docs/acmg/)

So maybe you can update the gene list of secondary findings in the ```cpsr``` pipeline. 

Thank you and have a good day!
Best,
Jianxiang

**Comment by sigven** [comment]
Hi @jxshi,

I updated the latest release (0.6.2) with genes from ACMG 3.0, although I have not mentioned this in the CHANGELOG. So they should be present already.

thanks,
Sigve

**Comment by jxshi** [comment]
Great! Cheers!
Have a great day!

Best,
Jianxiang
