### ISSUE TITLE
Error: `by` can't contain join column `GENOMIC_CHANGE` which is missing from RHS

### ISSUE THREAD

**Issue by vladsaveliev** [sigven/cpsr#4]
Another one (sorry :) ), during `cpsr-writer`, dockerized one as well:

```
2018-11-12 12:37:26 [INFO] TIER 3: Other unclassified variants - noncancer_phenotype: n = 0
Error: `by` can't contain join column `GENOMIC_CHANGE` which is missing from RHS
Execution halted
```

Attaching the test data for this run, and the command is as follows:

```
./cpsr.py --input_vcf cup__cup_tissue-normal.vcf.gz ~/git/pcgr cpsr_res grch37 ~/git/umccr/umccrise/umccrise/pcgr/cpsr.toml cup__cup_tissue-normal
```

[cpsr_test.zip](https://github.com/sigven/cpsr/files/2571919/cpsr_test.zip)

**Comment by sigven** [comment]
Thanks, Vlad! never be sorry, if it was not for you, bugs would be piling up more quickly:-) I'll have a look now.

**Comment by sigven** [comment]
Think this should be taken care of now.
