### ISSUE TITLE
adding clones IDs + child clone emerging outside parent clone 

### ISSUE THREAD

**Issue by LayalYasin** [sigven/cpsr#51]
Good after noon !
I have three questions please

is it possible to edit some code/parameters to fix this issue when you have a child clone originating outside its parent clone, like this picture:
<img width="209" alt="Screenshot 2023-12-20 at 14 26 00" src="https://github.com/sigven/cpsr/assets/32568878/2e710a64-867c-4f0b-8907-7804b8c98e3f">

Now in this second image you see for clones (two above and two below, and probably some hidden clones) starting to emerge at this timepoints, is it possible that we have all those emerging clones starting on the same vertical line ? if not, based on what is the starting point of those emerging clones chosen ?
<img width="309" alt="Screenshot 2023-12-20 at 14 26 11" src="https://github.com/sigven/cpsr/assets/32568878/e896354b-fe93-4522-b232-f0446a7e2454">

Finally, could we have IDs before the start of each clone ? to be able to differentiate them ?
<img width="135" alt="Screenshot 2023-12-20 at 14 26 19" src="https://github.com/sigven/cpsr/assets/32568878/d2a146e6-b163-4288-be74-ebc4072a4d12">

thanks a lot for your support !

**Comment by sigven** [comment]
Hi @LayalYasin,

Thanks for your message. It seems as if you have filed an issue in the wrong repository? CPSR does not deal with clonal analysis, it is a germline variant interpretation report engine, the functionality you are referring to is not part of CPSR.

kind regards,
Sigve

**Comment by LayalYasin** [comment]
oh sorry ! indeed wrong repo.
