### ISSUE TITLE
cpsr-gene-annotate - INFO - NO VEP BLOCK FOUND

### ISSUE THREAD

**Issue by ShimaaSherif** [sigven/cpsr#63]
Hello, I'm getting this error, while running the CPSR v2.03. However; the v1.02 was working fine on the same vcf file.

> - cpsr-summarise - INFO - CPSR - STEP 3: Cancer gene annotations with cpsr-summarise
> - cpsr-gene-annotate - WARNING - Picked VEP block for 1_36066715_T_C does not match virtual panel target genes - considering alternative consequences
> - cpsr-gene-annotate - WARNING - Picked VEP block for 1_45785983_CTTTTTTT_C does not match virtual panel target genes - considering alternative consequences
> - cpsr-gene-annotate - INFO - NO VEP BLOCK FOUND

Can you please assist?
Thank you so much.

**Comment by sigven** [comment]
Hi,

Thanks for reaching out:) Is this hg38? Can you show me the full command you are using? panel id etc?

best,
Sigve

**Comment by ShimaaSherif** [comment]
Hi Sigve, thank you for the fast response. 

Yes; grch38, here is the command: 

> docker run -it --rm -v /Path/:/PCGR --name Sample.ID sigven/pcgr:2.0.3 bash
> cpsr --input_vcf /Path/Sample.ID.germline.filtered.vcf.gz --output_dir /Path --genome_assembly grch38 --sample_id Sample.ID --refdata_dir /PCGR/PCGR/data2.0.3/ --vep_dir /PCGR/PCGR/data2.0.3/data/grch38/.vep --panel_id 42 --secondary_findings --gwas_findings --ignore_noncoding --pop_gnomad global --maf_upper_threshold 0.01 --classify_all --force_overwrite

Note: The PCGR v.2.03 (somatic variant) is working perfectly fine.

**Comment by sigven** [comment]
Closing this issue for now. The warning you encountered is a bit confusing, and I will try to remove this in a future release, but as stated above, it's not an error.

BTW: just released 2.1.0 over the weekend. Fresh data, re-calibration of classification thresholds.

best,
Sigve
