### ISSUE TITLE
--no-docker BSGenome package not installed

### ISSUE THREAD

**Issue by brucemoran** [sigven/cpsr#8]
Hi Sigve,

getting an error because 'BSgenome.Hsapiens.UCSC.hg19' isn't available running in --no-docker. Don't use conda so no idea how to fix, presume add to conda env?

Package(s) look great btw, building into NextFlow pipelines using Singularity so you may hear from me again=D

Thanks,

Bruce.

**Comment by sigven** [comment]
Dear Bruce,

Truly sorry for the late response to this issue. I am making a huge upgrade on this workflow at the moment, and I will have the guys that have added the `--no-docker` option look into this once i push the new release. Download an example report showing the new look [here](https://www.dropbox.com/s/7axgt8qrxfntnc6/example.cpsr.grch37.html?dl=0) if you like.

Updates coming soon!

best,
Sigve

**Comment by brucemoran** [comment]
Hi Sigve,

finally got time to get this running in a Singularity container in a Nextflow pipeline (thanks to @tsnowlan), first CPSR report found a veery significant mutation, so great! And report is perfect for clinicians to view. 

Also solved my issue here, see [the Singularity recipe ](https://github.com/brucemoran/Singularity/blob/master/tools/annotation/recipe.pcgr.CentOs7).

Thanks,

Bruce

**Comment by sigven** [comment]
Hi Bruce,
That's very cool! I am happy you got it working on your side. I'll do my best to follow up if you run into any other issues.

best,
Sigve
